# -*- coding: utf-8 -*-
"""MLR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CWHgab5U4OwxEaBnPA104X_aXNLKPoMm

# **Without Splitting Data**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/527 - Predictive Modeling/Team Project/Data.csv")

# Normalize features (Min-Max Scaling) to bring all values into the range [0,1]
df[['x1', 'x2']] = (df[['x1', 'x2']] - df[['x1', 'x2']].min()) / (df[['x1', 'x2']].max() - df[['x1', 'x2']].min())

# Convert dataframe to numpy arrays for calculations
X = df[['x1', 'x2']].values  # Independent variables (features)
y = df['y'].values  # Dependent variable (target)
n = len(y)  # Number of samples

# Add bias term (intercept) as the first column of X
X = np.c_[np.ones(n), X]  # Adds a column of ones for the intercept term

# Function to compute Mean Squared Error (MSE)
def compute_mse(X, y, theta):
    """Compute the Mean Squared Error (MSE)"""
    predictions = X.dot(theta)  # Compute predictions
    errors = predictions - y  # Compute errors
    mse = np.mean(errors**2)  # Calculate MSE
    return mse

# Function to perform gradient descent optimization
def gradient_descent(X, y, learning_rate, num_iterations):
    """Perform gradient descent optimization"""
    m, n = X.shape  # Number of samples (m) and features (n)
    theta = np.zeros(n)  # Initialize parameters (weights) to zero
    mse_log = []  # Store MSE for each iteration

    # Gradient Descent Loop
    for i in range(num_iterations):
        predictions = X.dot(theta)  # Compute predictions
        errors = predictions - y  # Compute errors (difference between predicted and actual values)
        gradients = (2/m) * X.T.dot(errors)  # Compute gradient of cost function
        theta -= learning_rate * gradients  # Update parameters using learning rate

        mse = compute_mse(X, y, theta)  # Compute new MSE
        mse_log.append(mse)  # Log MSE for visualization

        # Save MSE logs to a file in every iteration
        with open(f"MLRTraining[{num_iterations}][{learning_rate}]MSE.txt", "a") as log_file:
            log_file.write(f"Iteration {i+1}: MSE = {mse}\n")

    return theta, mse_log  # Return optimized parameters and MSE log

# Get custom user input for learning rate and number of iterations
learning_rate = float(input("Enter the learning rate (e.g., 0.01): "))
num_iterations = int(input("Enter the number of iterations (e.g., 1500): "))

# Train model using gradient descent
theta, mse_log = gradient_descent(X, y, learning_rate, num_iterations)

# Compute R-squared
y_pred = X.dot(theta)
ss_total = np.sum((y - np.mean(y)) ** 2)
ss_residual = np.sum((y - y_pred) ** 2)
r_squared = 1 - (ss_residual / ss_total)

# Save model parameters to a file
with open(f"MLRModelParameters_LR{learning_rate}_Iter{num_iterations}.txt", "w") as param_file:
    param_file.write(f"Learning Rate: {learning_rate}\n")
    param_file.write(f"Iterations: {num_iterations}\n")
    param_file.write(f"Final MSE: {mse_log[-1]}\n")
    param_file.write(f"Intercept: {theta[0]}\n")
    param_file.write(f"Slope x1: {theta[1]}\n")
    param_file.write(f"Slope x2: {theta[2]}\n")
    param_file.write(f"R-squared: {r_squared}\n")

# Print model parameters
print(f"\nModel results:")
print(f"Learning Rate: {learning_rate}")
print(f"Iterations: {num_iterations}")
print(f"Final MSE: {mse_log[-1]}")
print(f"Intercept: {theta[0]}")
print(f"Slope x1: {theta[1]}")
print(f"Slope x2: {theta[2]}")
print(f"R-squared: {r_squared}")

# Plot MSE over iterations to visualize convergence
plt.figure(figsize=(8,5))
plt.plot(range(num_iterations), mse_log, label="MSE over iterations", color="red")
plt.xlabel("Iterations")
plt.ylabel("Mean Squared Error")
plt.title("MSE per Iteration")
plt.legend()
plt.grid()
plt.savefig("MLR_MSE_Iteration.png")
plt.show()

# Scatter plot of actual vs predicted values
plt.figure(figsize=(8,5))
plt.scatter(range(n), y, label="Actual Values", color="blue")  # Actual values
plt.scatter(range(n), y_pred, label="Predicted Values", color="red", marker='x')  # Predicted values

# Draw vertical error lines between actual and predicted points
for i in range(n):
    plt.plot([i, i], [y[i], y_pred[i]], 'k-', linewidth=0.5)

plt.xlabel("Sample Index")
plt.ylabel("Y Values")
plt.title("Actual vs Predicted Values")
plt.legend()
plt.grid()
plt.savefig("MLR_Actual_vs_Predicted.png")
plt.show()

# Compare different learning rates and their final MSE values
learning_rates = [0.001, 0.01, 0.1]
results = {}

# Train model with different learning rates
for lr in learning_rates:
    theta_lr, mse_lr = gradient_descent(X, y, lr, num_iterations)
    results[lr] = mse_lr[-1]

# Convert results into a DataFrame and print
results_df = pd.DataFrame(results.items(), columns=["Learning Rate", "Final MSE"])
print(results_df)

import matplotlib.pyplot as plt

# Predefined learning rates
learning_rates = [0.001, 0.01, 0.1]
num_iterations = 1000

plt.figure(figsize=(10, 6))

# Plot MSE curves for each predefined learning rate
for lr in learning_rates:
    _, mse_log_predefined = gradient_descent(X, y, lr, num_iterations)
    plt.plot(range(num_iterations), mse_log_predefined, label=f"LR = {lr}")

# Add main model curve with correct length
plt.plot(range(len(mse_log)), mse_log, label=f"Main Model LR = {learning_rate}", linestyle='--', color='black')

# Styling the plot
plt.xlabel("Iterations")
plt.ylabel("Mean Squared Error")
plt.title("MSE per Iteration for Different Learning Rates + Main Model")
plt.legend()
plt.grid()

# Save and show the graph
plt.savefig("MLR_Multi_MSE_Comparison_With_Main_Model.png")
plt.show()

